/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TargetingRouteImport } from './routes/targeting'
import { Route as QueryRouteImport } from './routes/query'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as CompaniesRouteImport } from './routes/companies'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicInngestRouteImport } from './routes/api/public/inngest'
import { Route as ApiCronSignalsReconcileRouteImport } from './routes/api/cron/signals-reconcile'
import { Route as ApiCronScanSignalsRouteImport } from './routes/api/cron/scan-signals'
import { Route as ApiCronIntelScanRouteImport } from './routes/api/cron/intel-scan'

const TargetingRoute = TargetingRouteImport.update({
  id: '/targeting',
  path: '/targeting',
  getParentRoute: () => rootRouteImport,
} as any)
const QueryRoute = QueryRouteImport.update({
  id: '/query',
  path: '/query',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesRoute = CompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicInngestRoute = ApiPublicInngestRouteImport.update({
  id: '/api/public/inngest',
  path: '/api/public/inngest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronSignalsReconcileRoute = ApiCronSignalsReconcileRouteImport.update({
  id: '/api/cron/signals-reconcile',
  path: '/api/cron/signals-reconcile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronScanSignalsRoute = ApiCronScanSignalsRouteImport.update({
  id: '/api/cron/scan-signals',
  path: '/api/cron/scan-signals',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronIntelScanRoute = ApiCronIntelScanRouteImport.update({
  id: '/api/cron/intel-scan',
  path: '/api/cron/intel-scan',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/companies': typeof CompaniesRoute
  '/crm': typeof CrmRoute
  '/dashboard': typeof DashboardRoute
  '/events': typeof EventsRoute
  '/platform': typeof PlatformRoute
  '/portfolio': typeof PortfolioRoute
  '/query': typeof QueryRoute
  '/targeting': typeof TargetingRoute
  '/api/cron/intel-scan': typeof ApiCronIntelScanRoute
  '/api/cron/scan-signals': typeof ApiCronScanSignalsRoute
  '/api/cron/signals-reconcile': typeof ApiCronSignalsReconcileRoute
  '/api/public/inngest': typeof ApiPublicInngestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/companies': typeof CompaniesRoute
  '/crm': typeof CrmRoute
  '/dashboard': typeof DashboardRoute
  '/events': typeof EventsRoute
  '/platform': typeof PlatformRoute
  '/portfolio': typeof PortfolioRoute
  '/query': typeof QueryRoute
  '/targeting': typeof TargetingRoute
  '/api/cron/intel-scan': typeof ApiCronIntelScanRoute
  '/api/cron/scan-signals': typeof ApiCronScanSignalsRoute
  '/api/cron/signals-reconcile': typeof ApiCronSignalsReconcileRoute
  '/api/public/inngest': typeof ApiPublicInngestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/companies': typeof CompaniesRoute
  '/crm': typeof CrmRoute
  '/dashboard': typeof DashboardRoute
  '/events': typeof EventsRoute
  '/platform': typeof PlatformRoute
  '/portfolio': typeof PortfolioRoute
  '/query': typeof QueryRoute
  '/targeting': typeof TargetingRoute
  '/api/cron/intel-scan': typeof ApiCronIntelScanRoute
  '/api/cron/scan-signals': typeof ApiCronScanSignalsRoute
  '/api/cron/signals-reconcile': typeof ApiCronSignalsReconcileRoute
  '/api/public/inngest': typeof ApiPublicInngestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/companies'
    | '/crm'
    | '/dashboard'
    | '/events'
    | '/platform'
    | '/portfolio'
    | '/query'
    | '/targeting'
    | '/api/cron/intel-scan'
    | '/api/cron/scan-signals'
    | '/api/cron/signals-reconcile'
    | '/api/public/inngest'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/companies'
    | '/crm'
    | '/dashboard'
    | '/events'
    | '/platform'
    | '/portfolio'
    | '/query'
    | '/targeting'
    | '/api/cron/intel-scan'
    | '/api/cron/scan-signals'
    | '/api/cron/signals-reconcile'
    | '/api/public/inngest'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/companies'
    | '/crm'
    | '/dashboard'
    | '/events'
    | '/platform'
    | '/portfolio'
    | '/query'
    | '/targeting'
    | '/api/cron/intel-scan'
    | '/api/cron/scan-signals'
    | '/api/cron/signals-reconcile'
    | '/api/public/inngest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  CompaniesRoute: typeof CompaniesRoute
  CrmRoute: typeof CrmRoute
  DashboardRoute: typeof DashboardRoute
  EventsRoute: typeof EventsRoute
  PlatformRoute: typeof PlatformRoute
  PortfolioRoute: typeof PortfolioRoute
  QueryRoute: typeof QueryRoute
  TargetingRoute: typeof TargetingRoute
  ApiCronIntelScanRoute: typeof ApiCronIntelScanRoute
  ApiCronScanSignalsRoute: typeof ApiCronScanSignalsRoute
  ApiCronSignalsReconcileRoute: typeof ApiCronSignalsReconcileRoute
  ApiPublicInngestRoute: typeof ApiPublicInngestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/targeting': {
      id: '/targeting'
      path: '/targeting'
      fullPath: '/targeting'
      preLoaderRoute: typeof TargetingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/query': {
      id: '/query'
      path: '/query'
      fullPath: '/query'
      preLoaderRoute: typeof QueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies': {
      id: '/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof CompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/inngest': {
      id: '/api/public/inngest'
      path: '/api/public/inngest'
      fullPath: '/api/public/inngest'
      preLoaderRoute: typeof ApiPublicInngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/signals-reconcile': {
      id: '/api/cron/signals-reconcile'
      path: '/api/cron/signals-reconcile'
      fullPath: '/api/cron/signals-reconcile'
      preLoaderRoute: typeof ApiCronSignalsReconcileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/scan-signals': {
      id: '/api/cron/scan-signals'
      path: '/api/cron/scan-signals'
      fullPath: '/api/cron/scan-signals'
      preLoaderRoute: typeof ApiCronScanSignalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/intel-scan': {
      id: '/api/cron/intel-scan'
      path: '/api/cron/intel-scan'
      fullPath: '/api/cron/intel-scan'
      preLoaderRoute: typeof ApiCronIntelScanRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  CompaniesRoute: CompaniesRoute,
  CrmRoute: CrmRoute,
  DashboardRoute: DashboardRoute,
  EventsRoute: EventsRoute,
  PlatformRoute: PlatformRoute,
  PortfolioRoute: PortfolioRoute,
  QueryRoute: QueryRoute,
  TargetingRoute: TargetingRoute,
  ApiCronIntelScanRoute: ApiCronIntelScanRoute,
  ApiCronScanSignalsRoute: ApiCronScanSignalsRoute,
  ApiCronSignalsReconcileRoute: ApiCronSignalsReconcileRoute,
  ApiPublicInngestRoute: ApiPublicInngestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
